---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution == "Rocky"

  - name: install apache2 and packages
    dnf:
      name: 
        - httpd
        - php
        - php-cli
        - php-common
        - php-mbstring
        - php-mysqlnd
        - php-xml
        - php-gd
      state: latest
    when: ansible_distribution == "Rocky"

  - name: install apache2 and PHP 
    apt:
      name:
        - apache2
        - php
      state: latest
    when: ansible_distribution == "Debian"
